min_pr_homepage:
    path:     /
    defaults: { _controller: MinPRBundle:Default:index }

min_pr_mypage:
    path:    /{id}/
    defaults: { _controller: MinPRBundle:Hjem:oversikt }
    
    
min_pr_bilder:
    path:    /{avis}/bilde/{id}/
    defaults: { _controller: MinPRBundle:Bilder:lastned }