services:
    app.twig_extension:
        class: UKMNorge\DesignBundle\Twig\DatoExtension
        public: false
        tags:
            - { name: twig.extension }
#    ukm_design.example:
#        class: UKMNorge\DesignBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
